"""add phone number

Revision ID: 442d7918b451
Revises: e1286847a454
Create Date: 2023-04-11 06:01:14.587622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442d7918b451'
down_revision = 'e1286847a454'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
